#!/bin/bash
set -e
PYTHON='python3.10'  
cython -3 --verbose --embed -o build/notebook.c src/notebook.pyx
gcc -Os `python3-config --includes` build/notebook.c -l$PYTHON -o build/notebook

cp docs/notebook.ico /usr/share/icons/
cp build/notebook
